"""Visualization tab layout builder, EventBus wiring, and playback control callbacks.

DPG-aware module (imports ``dearpygui`` at module scope); backend modules must not
import from ``tabs/``.

BLE001 convention: every DPG callback wraps its body in
``try / except Exception: logger.exception(...)`` with a ``# noqa: BLE001``
marker so a callback error can never crash the render loop.

Circular-import note: ``_init_fps_overlay`` and ``_playback_tick`` live in
``playback.py``; ``create_visualization_tab`` reaches ``_init_fps_overlay`` via a
lazy ``from ... import playback as _pb`` inside the function body to avoid a
controls->playback->controls circular import.

``_CONTROL_PANEL_WIDTH`` is imported from ``render_loop`` (single owner); do NOT
redefine it here.
"""

from __future__ import annotations

import logging

import dearpygui.dearpygui as dpg

from floodlight_gui.core.event_bus import Events, bus
from floodlight_gui.core.optional_features import HAS_FFMPEG
from floodlight_gui.core.periods import period_display_to_internal, period_internal_to_display
from floodlight_gui.status_bar import FOOTER_HEIGHT_PX
from floodlight_gui.tabs._shared.error_helpers import (  # noqa: F401
    friendly_error_message,
    show_error_modal,
)
from floodlight_gui.tabs._shared.export_action import (
    _open_folder_picker as _viz_export_open_folder_picker,
)
from floodlight_gui.tabs._shared.export_action import (
    render_binary_export_action,
)
from floodlight_gui.tabs._shared.tab_header import add_tab_header
from floodlight_gui.tabs.visualization import state
from floodlight_gui.tabs.visualization.export_writers import (
    _make_image_writer,
    _make_video_writer,
    clip_frame_range,
)
from floodlight_gui.tabs.visualization.mouse_handlers import _register_mouse_handlers
from floodlight_gui.tabs.visualization.overlay_dispatch import (
    _on_model_fitted,
    _on_overlay_toggle,
    _on_voronoi_alpha,
)
from floodlight_gui.tabs.visualization.playback import (
    _jump_frames,
    _on_speed_changed,
    _set_speed_multiplier,
    _stop_playback_if_playing,
    _toggle_play_pause,
)
from floodlight_gui.tabs.visualization.render_loop import (
    _CONTROL_PANEL_WIDTH,  # single owner: render_loop.py; import here, do NOT redefine
    _DRAWLIST_CONTAINER_TAG,
    _DRAWLIST_INITIAL_HEIGHT,
    _DRAWLIST_INITIAL_WIDTH,
    _DRAWLIST_TAG,
    _on_data_loaded,
    _on_xy_stack_changed,
    initialize_visualization,
)
from floodlight_gui.tabs.visualization.timeline import (
    _TIMELINE_CONTAINER_TAG,
    _TIMELINE_HOVER_TAG,
    _TIMELINE_ROW_HEIGHT,
    _TIMELINE_TAG,
    _TIMELINE_WIDTH_INITIAL,
    _on_data_loaded_timeline,
    _on_frame_changed_timeline,
)
from floodlight_gui.theme import INFO

logger = logging.getLogger(__name__)

__all__ = ["create_visualization_tab"]

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_CONTROL_PANEL_HEIGHT = 700
_RIGHT_PANEL_HEIGHT = 700

# Retained for test_export_gating.py compatibility; the panel-internal button
# tag is generated by render_binary_export_action.
_EXPORT_IMAGE_BTN_TAG = "viz_export_image_btn"

# Teamsheet-driven on-canvas player-label dropdown. "Off" = no labels. The other
# entries are the VERBATIM column labels of the loaded teamsheets (no renaming,
# no fabrication), plus the always-available "xID" (the x-coordinate column
# index, derivable from the array position even with no teamsheet). When no
# teamsheet is loaded the combo collapses to just "Off" + "xID".
_LABEL_FIELD_OFF = "Off"
_LABEL_FIELD_XID = "xID"


# ---------------------------------------------------------------------------
# APP_INITIALIZED handler
# ---------------------------------------------------------------------------


def _on_app_initialized(app, **_):
    """Capture the app reference from the APP_INITIALIZED event."""
    state.app_instance = app


# Subscribe at module scope so it fires even before create_visualization_tab runs.
bus.subscribe(Events.APP_INITIALIZED, _on_app_initialized, priority=0)


# ---------------------------------------------------------------------------
# Tab entry point
# ---------------------------------------------------------------------------


def create_visualization_tab():
    """Build the Visualization tab: pitch canvas, playback controls, overlays, export.

    Creates all DPG widgets for the tab, registers mouse handlers, and subscribes
    to EventBus events. Must be called once during app startup inside an active
    DPG context.

    Notes
    -----
    DPG tags owned by this function (directly or via helpers called here):

    - ``viz_tab`` -- the DPG tab item
    - ``viz_content_wrap`` -- full-height child window wrapping all content
    - ``_DRAWLIST_CONTAINER_TAG``, ``_DRAWLIST_TAG`` -- pitch canvas container and drawlist
    - ``_TIMELINE_CONTAINER_TAG``, ``_TIMELINE_TAG``, ``_TIMELINE_HOVER_TAG`` -- Code-object
      timeline strip (hidden until Code data is available)
    - All tags created by ``_build_control_panel`` (period combo, team checkboxes,
      frame slider, transport buttons, overlay toggles, export panels)

    EventBus subscriptions wired here:

    - ``Events.DATA_LOADED`` -> ``_on_data_loaded`` (render_loop), priority 10
    - ``Events.DATA_LOADED`` -> ``_on_data_loaded_timeline`` (timeline), priority 10
    - ``Events.FRAME_CHANGED`` -> ``_on_frame_changed_timeline`` (timeline), priority 10
    - ``Events.MODEL_FITTED`` -> ``_on_model_fitted`` (overlay_dispatch), priority 10
    - ``Events.XY_STACK_CHANGED`` -> ``_on_xy_stack_changed`` (render_loop), priority 10

    Side-effects:

    - Calls ``_register_mouse_handlers()`` to attach a global DPG mouse handler.
    - Calls ``playback._init_fps_overlay()`` (lazy import to break the
      controls->playback->controls circular import).
    """
    with dpg.tab(label="Visualization", tag="viz_tab"):
        # Tab header mounts the unified data-context summary shared with all tabs.
        add_tab_header("visualization")

        with dpg.child_window(
            tag="viz_content_wrap",
            height=-FOOTER_HEIGHT_PX,
            border=False,
            autosize_x=True,
        ):
            dpg.add_text("Interactive Match Visualization", color=INFO)
            dpg.add_separator()

            with dpg.group(horizontal=True):
                # ----- Left panel: controls (fixed 350 px) -----
                with dpg.child_window(width=_CONTROL_PANEL_WIDTH, height=-1):
                    _build_control_panel()

                # ----- Right panel: drawlist + Code-object timeline strip -----
                with dpg.child_window(
                    width=-1, height=-1, tag=_DRAWLIST_CONTAINER_TAG, border=False
                ):
                    dpg.add_text(
                        "Load match data to begin",
                        tag="viz_plot_placeholder",
                    )
                    dpg.add_drawlist(
                        width=_DRAWLIST_INITIAL_WIDTH,
                        height=_DRAWLIST_INITIAL_HEIGHT,
                        tag=_DRAWLIST_TAG,
                        show=False,
                    )

                    # Code-object timeline strip (below pitch, above playback toolbar).
                    with dpg.child_window(
                        tag=_TIMELINE_CONTAINER_TAG,
                        width=_TIMELINE_WIDTH_INITIAL + 4,
                        height=_TIMELINE_ROW_HEIGHT + 6,
                        show=False,  # hidden until codes available
                        border=False,
                    ):
                        dpg.add_drawlist(
                            tag=_TIMELINE_TAG,
                            width=_TIMELINE_WIDTH_INITIAL,
                            height=_TIMELINE_ROW_HEIGHT,
                        )
                        dpg.add_text(
                            "",
                            tag=_TIMELINE_HOVER_TAG,
                            color=INFO,
                            show=False,
                        )

    # Register a global mouse handler for hover / click on the drawlist.
    _register_mouse_handlers()

    # Subscribe to event-bus signals (single wiring point for the subpackage).
    bus.subscribe(Events.DATA_LOADED, _on_data_loaded, priority=10)
    bus.subscribe(Events.DATA_LOADED, _on_data_loaded_timeline, priority=10)
    bus.subscribe(Events.FRAME_CHANGED, _on_frame_changed_timeline, priority=10)
    bus.subscribe(Events.MODEL_FITTED, _on_model_fitted, priority=10)
    bus.subscribe(Events.XY_STACK_CHANGED, _on_xy_stack_changed, priority=10)

    # Lazy import to avoid controls->playback->controls circular import.
    from floodlight_gui.tabs.visualization import playback as _pb

    _pb._init_fps_overlay()


# ---------------------------------------------------------------------------
# Control panel builder
# ---------------------------------------------------------------------------


def _build_control_panel():
    """Build all left-panel widgets: data selection, playback, overlays, export.

    Renders into the currently active DPG parent (a child_window created by
    ``create_visualization_tab``).

    Notes
    -----
    DPG tags owned by this function:

    - ``viz_period_selection`` -- period combo
    - ``viz_team_checkboxes`` -- group container for per-team checkboxes
    - ``viz_frame_slider``, ``viz_frame_info`` -- frame navigation
    - ``viz_jump_back_large``, ``viz_jump_back``, ``viz_play_pause``,
      ``viz_jump_forward``, ``viz_jump_forward_large`` -- transport buttons
    - ``viz_play_speed``, ``viz_fps_info`` -- speed slider and info text
    - ``viz_speed_0_5x``, ``viz_speed_1x``, ``viz_speed_1_5x``, ``viz_speed_2x``
      -- speed preset buttons
    - ``viz_overlay_header``, ``viz_overlay_placeholder``, ``viz_overlay_hull``,
      ``viz_overlay_voronoi``, ``viz_voronoi_alpha_spacer``, ``viz_voronoi_alpha_label``,
      ``viz_voronoi_alpha``, ``viz_overlay_status`` -- overlay section
    - ``viz_label_field`` -- player-label column combo
    - ``viz_player_info``, ``viz_status`` -- info and status text
    - ``viz_step5_export_header``, ``viz_export_shared_filename``,
      ``viz_export_change_folder_btn``, ``viz_export_status`` -- export panel
    """

    # -- Data Selection --
    with dpg.collapsing_header(label="Data Selection", default_open=True, closable=False):
        dpg.add_text("Select Period:")
        dpg.add_combo(
            items=["No data loaded"],
            default_value="No data loaded",
            callback=_on_period_changed,
            width=200,
            tag="viz_period_selection",
        )
        dpg.add_spacer(height=10)
        dpg.add_text("Select Teams to Display:")
        dpg.add_group(tag="viz_team_checkboxes")

    dpg.add_separator()

    # -- Playback Controls --
    with dpg.collapsing_header(label="Playback Controls", default_open=True, closable=False):
        dpg.add_text("Frame Navigation:")
        dpg.add_slider_int(
            label="Frame",
            default_value=0,
            min_value=0,
            max_value=100,
            callback=_on_frame_slider_in_controls,
            tag="viz_frame_slider",
            width=280,
        )
        dpg.add_text("", tag="viz_frame_info")
        dpg.add_spacer(height=10)

        # ASCII glyphs only for transport buttons; no Unicode media symbols.
        with dpg.group(horizontal=True):
            dpg.add_button(
                label="|<", callback=lambda: _jump_frames(-100), width=40, tag="viz_jump_back_large"
            )
            with dpg.tooltip("viz_jump_back_large"):
                dpg.add_text("Jump back 100 frames")
            dpg.add_button(
                label="<<", callback=lambda: _jump_frames(-10), width=40, tag="viz_jump_back"
            )
            with dpg.tooltip("viz_jump_back"):
                dpg.add_text("Step back 10 frames")
            dpg.add_button(label=">", callback=_toggle_play_pause, width=40, tag="viz_play_pause")
            with dpg.tooltip("viz_play_pause"):
                dpg.add_text("Play / Pause")
            dpg.add_button(
                label=">>", callback=lambda: _jump_frames(10), width=40, tag="viz_jump_forward"
            )
            with dpg.tooltip("viz_jump_forward"):
                dpg.add_text("Step forward 10 frames")
            dpg.add_button(
                label=">|",
                callback=lambda: _jump_frames(100),
                width=40,
                tag="viz_jump_forward_large",
            )
            with dpg.tooltip("viz_jump_forward_large"):
                dpg.add_text("Jump forward 100 frames")

        dpg.add_spacer(height=10)
        dpg.add_text("Playback Speed:")
        dpg.add_slider_int(
            label="FPS",
            default_value=25,
            min_value=1,
            max_value=60,
            callback=_on_speed_changed,
            width=280,
            tag="viz_play_speed",
        )
        with dpg.group(horizontal=True):
            dpg.add_button(
                label="0.5x",
                width=45,
                callback=lambda: _set_speed_multiplier(0.5),
                tag="viz_speed_0_5x",
            )
            dpg.add_button(
                label="1x",
                width=45,
                callback=lambda: _set_speed_multiplier(1.0),
                tag="viz_speed_1x",
            )
            dpg.add_button(
                label="1.5x",
                width=45,
                callback=lambda: _set_speed_multiplier(1.5),
                tag="viz_speed_1_5x",
            )
            dpg.add_button(
                label="2x",
                width=45,
                callback=lambda: _set_speed_multiplier(2.0),
                tag="viz_speed_2x",
            )
        dpg.add_text("", tag="viz_fps_info", wrap=200)

    dpg.add_separator()

    # -- Overlay Controls --
    with dpg.collapsing_header(
        label="Overlays", default_open=True, tag="viz_overlay_header", closable=False
    ):
        dpg.add_combo(
            label="Player label",
            items=[_LABEL_FIELD_OFF],
            default_value=_LABEL_FIELD_OFF,
            callback=_on_label_field_changed,
            tag="viz_label_field",
            width=150,
        )
        dpg.add_spacer(height=5)

        dpg.add_text(
            "No fitted models yet. Fit a Convex Hull or Discrete Voronoi "
            "in the Model tab to enable overlays here.",
            tag="viz_overlay_placeholder",
            wrap=280,
        )
        dpg.add_checkbox(
            label="Show Convex Hulls",
            default_value=False,
            show=False,
            callback=_on_overlay_toggle,
            tag="viz_overlay_hull",
            user_data="hull",
        )
        dpg.add_checkbox(
            label="Show Voronoi",
            default_value=False,
            show=False,
            callback=_on_overlay_toggle,
            tag="viz_overlay_voronoi",
            user_data="voronoi",
        )
        dpg.add_spacer(height=5, tag="viz_voronoi_alpha_spacer", show=False)
        dpg.add_text("Voronoi Opacity:", tag="viz_voronoi_alpha_label", show=False)
        dpg.add_slider_float(
            default_value=0.3,
            min_value=0.0,
            max_value=1.0,
            callback=_on_voronoi_alpha,
            width=200,
            tag="viz_voronoi_alpha",
            show=False,
        )
        dpg.add_spacer(height=5)
        dpg.add_text("No models fitted", tag="viz_overlay_status", wrap=280)

    dpg.add_separator()

    # -- Player Info --
    with dpg.collapsing_header(label="Player Info", default_open=True, closable=False):
        dpg.add_text("Hover over a player for details.", tag="viz_player_info", wrap=300)

    dpg.add_separator()

    # -- Status --
    dpg.add_text("Status:")
    dpg.add_text("Ready - Load data to begin", tag="viz_status", wrap=300)
    dpg.add_spacer(height=10)

    # Visualization Export panel.
    with dpg.collapsing_header(
        label="Step 5: Export",
        default_open=True,
        closable=False,
        tag="viz_step5_export_header",
    ):
        dpg.add_spacer(height=5)

        dpg.add_input_text(
            hint="Filename (leave blank for auto-generated)",
            tag="viz_export_shared_filename",
            width=280,
        )
        dpg.add_button(
            label="Change folder...",
            callback=_viz_export_open_folder_picker,
            tag="viz_export_change_folder_btn",
        )
        dpg.add_separator()
        dpg.add_spacer(height=5)

        render_binary_export_action(
            "viz_step5_export_header",
            tab_name="viz_image",
            artifact_name="frame",
            formats=["PNG", "SVG", "PDF"],
            writer_for_format={
                "PNG": _make_image_writer("png"),
                "SVG": _make_image_writer("svg"),
                "PDF": _make_image_writer("pdf"),
            },
            label="Export Image",
            status_tag="viz_export_status",
            filename_input_tag="viz_export_shared_filename",
            kind="visualization_image",
            viz_mode="frame",
            enabled=True,
            n_provider=lambda: int(state.viz_state.get("current_frame", 0)),
            render_change_folder=False,
            render_status=False,
        )

        # clip_frame_range() is the single source for start/end so the click-time
        # providers and the writer always agree on the frame range.
        def _video_n_provider() -> int:
            """Return the clamped start_frame at click time."""
            return clip_frame_range()[0]

        def _video_end_provider() -> int:
            """Return the clamped end_frame at click time."""
            return clip_frame_range()[1]

        render_binary_export_action(
            "viz_step5_export_header",
            tab_name="viz_video",
            artifact_name="clip",
            formats=["MP4"],
            writer_for_format={"MP4": _make_video_writer()},
            label="Export Video",
            status_tag="viz_export_status",
            filename_input_tag="viz_export_shared_filename",
            kind="visualization_video",
            viz_mode="clip",
            enabled=HAS_FFMPEG,
            ffmpeg_tooltip=(
                "Video export needs the optional 'video' extra. Install it with:\n"
                '    pip install "floodlight-gui[video]"\n'
                "This bundles ffmpeg via imageio-ffmpeg, so no separate ffmpeg "
                "download or system install is needed. Restart the app afterwards."
            ),
            n_provider=_video_n_provider,
            end_provider=_video_end_provider,
            render_change_folder=False,
            render_status=False,
            inline_widget_factory=lambda: dpg.add_input_int(
                label="Clip length (s)",
                default_value=5,
                min_value=1,
                min_clamped=True,
                width=70,
                tag="viz_video_clip_length",
            ),
        )

        dpg.add_spacer(height=4)
        dpg.add_text("Status: Ready", tag="viz_export_status")


# ---------------------------------------------------------------------------
# Frame-slider callback (thin shim so playback.py does not need to import controls)
# ---------------------------------------------------------------------------


def _on_frame_slider_in_controls(sender, app_data):
    """Delegate the frame-slider DPG callback to ``playback._on_frame_slider``."""
    from floodlight_gui.tabs.visualization.playback import _on_frame_slider

    _on_frame_slider(sender, app_data)


# ---------------------------------------------------------------------------
# Controls update helpers
# ---------------------------------------------------------------------------


def _update_controls_from_data():
    """Refresh period combo and team checkboxes from loaded data."""
    if not state.app_instance or not state.app_instance.loaded_data:
        return

    temporal_divisions = state.app_instance.get_temporal_divisions()
    team_names = state.app_instance.get_team_names()

    items = []
    for d in temporal_divisions:
        display = period_internal_to_display(d)
        if display == d:
            display = d.replace("_", " ").title()
        items.append(display)

    current_internal = state.viz_state.get("selected_half")
    if current_internal in temporal_divisions:
        target_internal = current_internal
    else:
        target_internal = temporal_divisions[0] if temporal_divisions else "firstHalf"

    if dpg.does_item_exist("viz_period_selection"):
        dpg.configure_item("viz_period_selection", items=items)
        if items:
            target_display = period_internal_to_display(target_internal)
            if target_display == target_internal:
                target_display = target_internal.replace("_", " ").title()
            if target_display not in items and items:
                target_display = items[0]
                target_internal = temporal_divisions[0] if temporal_divisions else "firstHalf"
            dpg.set_value("viz_period_selection", target_display)
    if temporal_divisions:
        state.viz_state["selected_half"] = target_internal

    # Team checkboxes
    if dpg.does_item_exist("viz_team_checkboxes"):
        dpg.delete_item("viz_team_checkboxes", children_only=True)

    state.viz_state["selected_teams"] = {}

    for team in team_names:
        xy_obj = None
        for period in temporal_divisions:
            from floodlight_gui.core.xy_access import get_xy_for_period_team

            xy_obj = get_xy_for_period_team(state.app_instance, period, team)
            if xy_obj is not None:
                break
        if xy_obj is None:
            continue
        checkbox_tag = f"viz_show_{team.lower().replace(' ', '_')}"
        dpg.add_checkbox(
            label=team,
            default_value=True,
            callback=_on_team_checkbox,
            tag=checkbox_tag,
            parent="viz_team_checkboxes",
        )
        state.viz_state["selected_teams"][team] = True


def _update_frame_range():
    """Compute max_frames for the selected period and configure the slider."""
    from floodlight_gui.core.xy_access import get_xy_for_period_team

    team_names = state.viz_state["cached_team_names"]
    if team_names is None:
        return

    half = state.viz_state["selected_half"]

    max_frames = 0
    for team in team_names:
        xy_obj = get_xy_for_period_team(state.app_instance, half, team)
        if xy_obj is not None and hasattr(xy_obj, "xy"):
            max_frames = max(max_frames, xy_obj.xy.shape[0] - 1)

    state.viz_state["max_frames"] = max_frames
    state.viz_state["current_frame"] = 0

    if dpg.does_item_exist("viz_frame_slider"):
        dpg.configure_item("viz_frame_slider", max_value=max_frames)
        dpg.set_value("viz_frame_slider", 0)

    _update_frame_info()


def _update_frame_info():
    """Update the frame counter text widget with current frame, total, and percentage."""
    frame = state.viz_state["current_frame"]
    total = state.viz_state["max_frames"]
    pct = (frame / total * 100) if total > 0 else 0.0
    dpg.set_value("viz_frame_info", f"Frame: {frame}/{total} ({pct:.1f}%)")


def _update_fps_info():
    """Update the FPS info display with original FPS, current FPS, and speed ratio."""
    if state.app_instance and state.app_instance.loaded_data:
        try:
            original_fps = state.app_instance.get_fps()
            current_fps = state.viz_state["play_speed"]
            speed = current_fps / original_fps if original_fps else 0
            dpg.set_value(
                "viz_fps_info",
                f"Original: {original_fps:.1f} FPS\nCurrent: {current_fps} FPS\nSpeed: {speed:.2f}x",  # noqa: E501
            )
        except (AttributeError, TypeError, ZeroDivisionError) as e:
            logger.warning("Error updating FPS info: %s", e)
    else:
        dpg.set_value("viz_fps_info", "Load data to see FPS info")


# ---------------------------------------------------------------------------
# Callbacks
# ---------------------------------------------------------------------------


def _on_period_changed(sender, app_data):
    """Handle period combo selection change."""
    _stop_playback_if_playing("Period changed")

    temporal_divisions = state.app_instance.get_temporal_divisions() if state.app_instance else []
    half_name = period_display_to_internal(app_data) if app_data else None
    if half_name is None or (half_name not in temporal_divisions and temporal_divisions):
        items = dpg.get_item_configuration("viz_period_selection").get("items", [])
        try:
            idx = items.index(app_data)
            half_name = temporal_divisions[idx]
        except (ValueError, IndexError):
            half_name = temporal_divisions[0] if temporal_divisions else "firstHalf"

    state.viz_state["selected_half"] = half_name

    if state.viz_state["initialized"]:
        initialize_visualization()


def _on_team_checkbox(sender, app_data):
    """Handle team visibility checkbox toggle."""
    from floodlight_gui.tabs.visualization.render_loop import _render_current_frame

    team_names = state.viz_state["cached_team_names"]
    if team_names is None:
        return

    renderer = state.viz_state["player_renderer"]

    for team in team_names:
        tag = f"viz_show_{team.lower().replace(' ', '_')}"
        if dpg.does_item_exist(tag):
            visible = dpg.get_value(tag)
            state.viz_state["selected_teams"][team] = visible
            if renderer is not None:
                try:
                    renderer.set_team_visible(team, visible)
                except SystemError as e:
                    logger.warning("Error toggling team %s: %s", team, e)

    _render_current_frame()


def _on_label_field_changed(sender, app_data):
    """Operator chose a teamsheet column (or 'Off') for on-canvas player labels."""
    renderer = state.viz_state.get("player_renderer")
    if renderer is None:
        return
    try:
        from floodlight_gui.tabs.visualization.render_loop import _render_current_frame

        if not app_data or app_data == _LABEL_FIELD_OFF:
            renderer.set_labels_visible(False)
            renderer.set_label_resolver(None)
            _render_current_frame()  # reflect immediately, not on the next tick
            return

        from floodlight_gui.core.player_mapping import teamsheet_column_values

        column = app_data
        teamsheet = getattr(state.app_instance, "teamsheet", None) if state.app_instance else None
        teams = state.viz_state.get("cached_team_names") or []
        # Precompute {team: [value per col_index]} once so the per-frame resolver
        # is a cheap list index, never a DataFrame read.
        per_team = {team: teamsheet_column_values(teamsheet, team, column) for team in teams}

        def _resolver(team: str, idx: int, _col=column, _map=per_team) -> str | None:
            values = _map.get(team) or []
            if 0 <= idx < len(values) and values[idx] is not None:
                return values[idx]
            # xID is the x-coordinate column index -- always derivable from the
            # array position even when the teamsheet doesn't carry it.
            if _col == _LABEL_FIELD_XID:
                return str(idx)
            return None

        renderer.set_label_resolver(_resolver)
        renderer.set_labels_visible(True)
        _render_current_frame()  # reflect immediately, not on the next tick
    except SystemError as exc:
        logger.warning("Error applying player label field (DPG item missing): %s", exc)


def _populate_label_field_combo() -> None:
    """Refresh the player-label combo from the loaded teamsheets' column labels."""
    if state.app_instance is None or not getattr(state.app_instance, "loaded_data", None):
        return
    if not dpg.does_item_exist("viz_label_field"):
        return

    from floodlight_gui.core.player_mapping import teamsheet_columns_for

    teams = state.viz_state.get("cached_team_names") or []
    teamsheet = getattr(state.app_instance, "teamsheet", None)
    if not teams and isinstance(teamsheet, dict):
        teams = list(teamsheet.keys())

    # Verbatim teamsheet column labels (none when no teamsheet is loaded), plus
    # the always-available xID. No fabricated / synthesized fields.
    columns = teamsheet_columns_for(teamsheet, teams)
    fields = [_LABEL_FIELD_XID] + [c for c in columns if c != _LABEL_FIELD_XID]
    items = [_LABEL_FIELD_OFF] + fields
    try:
        current = dpg.get_value("viz_label_field") or _LABEL_FIELD_OFF
        dpg.configure_item("viz_label_field", items=items)
        if current not in items:
            dpg.set_value("viz_label_field", _LABEL_FIELD_OFF)
            _on_label_field_changed(None, _LABEL_FIELD_OFF)
    except SystemError as exc:
        logger.debug("populate label combo failed: %s", exc)
